# Generated by Django 4.2.29 on 2026-04-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_otp',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_otp',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
