# Generated by Django 4.2.29 on 2026-04-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_devicetoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("SUPPORT", "Support"),
                    ("CUSTOMER", "Customer"),
                    ("PROVIDER", "Provider"),
                ],
                default="CUSTOMER",
                max_length=16,
            ),
        ),
    ]
